language: node_js
node_js:
  - "11.6.0"
cache:
  directories:
    - node_modules
env:
  - CI=true

before_deploy:
  - npm install netlify-cli@latest -g
  - npm run build

deploy:
  provider: script
  script: DEBUG=* netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_PUBLISH_KEY -p --dir ./dist
  skip_cleanup: true
  on:
    branch: master

after_success:
  - chmod +x ./publish.sh
  - ./publish.sh